-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 12:07:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CST236Milestone
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CST236Milestone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CST236Milestone` DEFAULT CHARACTER SET utf8 ;
USE `CST236Milestone` ;

-- -----------------------------------------------------
-- Table `CST236Milestone`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CST236Milestone`.`USERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` VARCHAR(45) NOT NULL,
  `LASTNAME` VARCHAR(45) NOT NULL,
  `ROLE` INT NOT NULL,
  `USERNAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CST236Milestone`.`ADDRESSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CST236Milestone`.`ADDRESSES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ADDRESSTYPE` INT NOT NULL,
  `ISDEFAULT` VARCHAR(45) NOT NULL,
  `STREET` VARCHAR(45) NOT NULL,
  `CITY` VARCHAR(45) NOT NULL,
  `STATE` VARCHAR(45) NOT NULL,
  `POSTALCODE` VARCHAR(45) NOT NULL,
  `USERS_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ADDRESSES_USERS_idx` (`USERS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ADDRESSES_USERS`
    FOREIGN KEY (`USERS_ID`)
    REFERENCES `CST236Milestone`.`USERS` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CST236Milestone`.`PRODUCTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CST236Milestone`.`PRODUCTS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PRODUCTNAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` TEXT(200) NOT NULL,
  `PRICE` FLOAT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CST236Milestone`.`ORDERDETAILS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CST236Milestone`.`ORDERDETAILS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `QUANTITY` INT NOT NULL,
  `CURRENTPRICE` FLOAT NOT NULL,
  `CURRENTDESCRIPTION` TEXT(200) NOT NULL,
  `ORDERS_ID` INT NOT NULL,
  `PRODUCTS_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ORDERDETAILS_PRODUCTS1_idx` (`PRODUCTS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ORDERDETAILS_PRODUCTS1`
    FOREIGN KEY (`PRODUCTS_ID`)
    REFERENCES `CST236Milestone`.`PRODUCTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CST236Milestone`.`ORDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CST236Milestone`.`ORDERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATE` DATETIME NOT NULL,
  `USERS_ID` INT NOT NULL,
  `ADDRESSES_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ORDERS_USERS1_idx` (`USERS_ID` ASC, `ADDRESSES_ID` ASC) VISIBLE,
  INDEX `fk_ORDERS_ADDRESSES1_idx` (`ADDRESSES_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ORDERS_USERS1`
    FOREIGN KEY (`USERS_ID` , `ADDRESSES_ID`)
    REFERENCES `CST236Milestone`.`USERS` (`ID` , `ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ORDERS_ADDRESSES1`
    FOREIGN KEY (`ADDRESSES_ID`)
    REFERENCES `CST236Milestone`.`ADDRESSES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
